### ISSUE TITLE
Support sending publish options

### ISSUE THREAD

**Issue by hkdobrev** [DrewML/chrome-webstore-upload#13]
I have an extension which is published to testers, but not to the general public yet. I'd still like to update it automatically through the Chrome Web Store and continuous integration.

When I perform the publish request through the CLI client I get the following 400 error:

```json
{
  "error": {
    "errors": [
      {
        "domain": "global",
        "reason": "badRequest",
        "message": "Publish condition not met: This item is current published to trusted testers. To publish it to everyone, you must unpublish it first. To keep publishing it to trusted testers, set publish_to_trusted_testers to true in the request."
      }
    ],
    "code": 400,
    "message": "Publish condition not met: This item is current published to trusted testers. To publish it to everyone, you must unpublish it first. To keep publishing it to trusted testers, set publish_to_trusted_testers to true in the request."
  }
}
```

Would you consider support of passing options to the body of the `publish` request so this case could be covered? Thanks!

**Comment by hkdobrev** [comment]
Oops! I went ahead to implement this and when I took a closer look at the tests I've found that the `target` argument is actually something which supports that. I hope someone finds my issue useful someday 😅

**Comment by bfred-it** [comment]
Can you let me know if the argument actually works? In the cli version someone was having trouble with it.

**Comment by hkdobrev** [comment]
@bfred-it I've created https://github.com/DrewML/chrome-webstore-upload-cli/pull/29 because I couldn't find a way to use it through the CLI. Please give me a hint if there's something I've missed! Thank you! 🙏
