### ISSUE TITLE
Group Publishing

### ISSUE THREAD

**Issue by blargity** [DrewML/chrome-webstore-upload#15]
First off, thanks for this module! It's been working for us for a good long while.

We recently moved our extension from individual publishing to group publishing. Now we're getting this back from the Google API:

```
(node:4205) UnhandledPromiseRejectionWarning: HTTPError: Response code 400 (Bad Request)
    at stream.catch.then.data (/home/travis/build/toolkit-for-ynab/toolkit-for-ynab/node_modules/got/index.js:123:13)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

I went through the steps again to get a new refresh token and set that up but I'm still having the same error. Does anyone happen to know how to set this module up to work with group publishing?

**Comment by DrewML** [comment]
> Does anyone happen to know how to set this module up to work with group publishing?

I personally have no idea how. I haven't looked at the API in quite a bit of time (@bfred-it has been doing an amazing job managing contributions). If you happen to figure it out, though, we'd certainly appreciate the contribution, whether it's code or docs.

**Comment by joshmadewell** [comment]
I work with @blargity on the project we were seeing this issue from. It looks like whatever was wrong has been fixed on Google's side since we've not changed our implementation and group publishing is now working...

We can probably close this issue now! But either way, thanks for the response @DrewML
