### ISSUE TITLE
window.prompt closes activating different window

### ISSUE THREAD

**Issue by gabrieljoelc** [DrewML/chrome-webstore-upload#17]
Getting
> A window.prompt() dialog generated by this page was suppressed because this page is not the active tab of the front window. Please make sure your dialogs are triggered by user interactions to avoid this situation. https://www.chromestatus.com/feature/5637107137642496

when running the "Run this in your browser console" step in ["How to generate Google API keys"](https://github.com/DrewML/chrome-webstore-upload/blob/master/How%20to%20generate%20Google%20API%20keys.md).

Version 65.0.3325.181 (Official Build) (64-bit)
Windows 10

Maybe this should be ported to a bash script since we'll be running it in the output in the terminal.

**Comment by gabrieljoelc** [comment]
What about something as simple as this?
```
$CLIENT_ID=[client_id]
$CLIENT_SECRET=[client_secret]
$AUTHCODE=[authcode]
curl "https://accounts.google.com/o/oauth2/token" --data-urlencode "client_id=$CLIENT_ID" --data-urlencode "client_secret=$CLIENT_SECRET" --data-url
ncode "code=$AUTHCODE" --data-urlencode "grant_type=authorization_code" --data-urlencode "redirect_uri=urn:ietf:wg:oauth:2.0:oob"
```

A disadvantage is the environment variable stays in the session unless the user closes it.

**Comment by bfred-it** [comment]
Where are you running this? You have to run it in the console of an active tab, it should work. It’s not bash script because not all computers have bash. PR welcome to **add** a one-line bash version with the three prompts as an alternative.

**Comment by gabrieljoelc** [comment]
@bfred-it I was running it in a tab with the page that gives you the `authcode`.

Not all computers have `curl` either so I made the assumption that bash was assumed.

ok I can do that.

**Comment by nwingert** [comment]
For what it's worth, I had trouble with this step also. The popup in the current tab won't allow selection of any information on the background page for copy/paste, and trying to grab the requested credentials from anywhere else causes the popup to close as discussed above. I'm not very experienced with the dev toolbox in chrome yet so maybe I'm missing something obvious, but I don't see any way to complete this step without manually inputting all of the credentials requested which seems tedious and error-prone.
