### ISSUE TITLE
Could you make it support firefox addons upload or is there another project could do this?

### ISSUE THREAD

**Issue by cnwangjie** [DrewML/chrome-webstore-upload#18]
Hi!

I am developing an extension, it could be used in chrome and firefox. I tried to find a way to auto publish for chrome and firefox, until now I found this project and it works very well. Very thanks for your great work and I need not to upload to chrome webstore manually. But is there a way to upload to firefox addons automatically?

Best Regards

**Comment by Narno** [comment]
Hello @cnwangjie, check this comment: https://github.com/mozilla/web-ext/issues/804#issuecomment-302588357

**Comment by cnwangjie** [comment]
@Narno Although it seems that it is not maintained, it is available for now. Thank you.

**Comment by bfred-it** [comment]
Also https://github.com/LinusU/wext-shipit
