### ISSUE TITLE
googleapis.com 404 on every resource.

### ISSUE THREAD

**Issue by Rambou** [DrewML/chrome-webstore-upload#34]
After debugging i've noticed that `https://www.googleapis.com/upload/chromewebstore/v1.1/items/{MY_EXTENTION_ID}`
returns 404 not found. Are googleapis for chrome web store down or closed?

**Comment by fregante** [comment]
Is it possible that the ID has spaces or extra characters? 404 means that the API can’t find the ID on their servers
