### ISSUE TITLE
Documentation out of date, 'other' not an option

### ISSUE THREAD

**Issue by ELepolt** [DrewML/chrome-webstore-upload#36]
Step 11 is out of date. I made the assumption to use 'Chrome App' and selecting that does not give me a client secret.

<img width="814" alt="Screen Shot 2020-05-14 at 3 23 13 PM" src="https://user-images.githubusercontent.com/1465938/81987730-788a1f00-95f7-11ea-9c8e-cac5a958fe9e.png">

**Comment by fregante** [comment]
Can you double-check your process? I still see this:

<img width="685" alt="" src="https://user-images.githubusercontent.com/1402241/81989655-f07b3800-963d-11ea-9ce3-507f36f5e730.png">

**Comment by ELepolt** [comment]
https://youtu.be/W5k2BuxFFBo

Please let me know if I didn't follow something correctly.

**Comment by fregante** [comment]
Looks right. It's weird because I just tried with a new account and new project and I still get the old UI.

Perhaps try Desktop app or any other item that doesn't require platform-specific info like "Android store URL"

**Comment by ELepolt** [comment]
Desktop App gives me a client secret. You da man

**Comment by fregante** [comment]
Thank you for the update! Guide updated: https://github.com/DrewML/chrome-webstore-upload/commit/444e33518d6bf7c0477b217c48e789ee42c4355a
