### ISSUE TITLE
uploadExisting throwing error: Cannot destructure property 'headers' of 'globalRequest.options' as it is undefined

### ISSUE THREAD

**Issue by Baegus** [DrewML/chrome-webstore-upload#41]
For some reason, when I try to upload a ZIP to the Web Store using the "uploadExisting" method, it is now throwing an error:
Cannot destructure property 'headers' of 'globalRequest.options' as it is undefined

The same script worked yesterday... Any ideas?

**Comment by fregante** [comment]
Did you update to the latest version in the meanwhile or are you completely sure it’s the same exact version in both runs?

**Comment by Baegus** [comment]
It's possible that the package version was different, since I'm running it from GitLab CI.

**Comment by darkobits** [comment]
Also ran into this issue when upgrading from `0.2.2` to `0.4.0`. Reverted to `0.2.2` and the issue was resolved.

**Comment by fregante** [comment]
Ok, I reverted the `got` update once again. v0.4.1 is now identical to v0.3.1 and v0.2.2.

cc @fire015

**Comment by fregante** [comment]
The code on `master` is unchanged however and the tests need to be fix to mock the HTTP responses instead of `got`’s.

**Comment by fire015** [comment]
@fregante looking at this quickly, if you install 0.4.0 you get a newer version of `got` (11.6.0 instead of 11.5.2 which is what we based the changes on). I would suggest you either commit a `package-lock.json` file locking to 11.5.2 or change package.json to `"got": "~11.5.2"`. There is no need to go back to the old library.

**Comment by fregante** [comment]
That'd explain why it apparently worked for @Baegus 2 days ago but not yesterday (right before and after [11.6.0](https://github.com/sindresorhus/got/releases/tag/v11.6.0)), but minor releases should not be breaking. Is this a `got` error?

**Comment by szmarczak** [comment]
Good catch! I'll try to fix this on Sunday or Monday. I have just moved to a different flat.

**Comment by fregante** [comment]
> I would suggest you either commit a `package-lock.json` file locking to 11.5.2 or change package.json to `"got": "~11.5.2"`. There is no need to go back to the old library.

We can't publish locks, they're ignored when the module is installed as a dependency. However we can use `"got": "11.5.2"` in package.json: 0cae205

This has been published as v0.4.2 with the new got. Sorry for the semver mess for 0.4.1

**Comment by szmarczak** [comment]
@fregante I think for the workaround you can set `responseType` to `json` and `resolveBodyOnly` to `true`. It should give the same as `promise.json()`.

**Comment by fregante** [comment]
Thank you! I think we're ok at the moment with 11.5.2, I'll just update the dependency when https://github.com/sindresorhus/got/issues/1438 is done. No rush
