### ISSUE TITLE
403 "access_denied" trying to get refresh token

### ISSUE THREAD

**Issue by TheExGenesis** [DrewML/chrome-webstore-upload#44]
![image](https://user-images.githubusercontent.com/7385326/102634049-37d42480-4149-11eb-9c8d-2e5842204304.png)

I followed the steps after requesting credentials as both Desktop App and Chrome App. Getting access_denied using the exact same account to log in.

**Comment by fregante** [comment]
Make sure you follow every instruction on the screen, hoping that they didn’t change the requirements. Technically this is not an issue with this package so you can try referring to the API’s own documentation if necessary.

**Comment by kiprasmel** [comment]
I managed to only reach step 13 -- after pasting in the link with my clientID, console logs an error and after selecting my own owner account, I get this:

![image](https://user-images.githubusercontent.com/29430509/105446892-c45b9080-5c7b-11eb-91d4-61106aef6b6b.png)

**Comment by fregante** [comment]
You were right, Google once again added more requirements and steps… I updated and guide and followed it again on a new "project" and I think it works now 🤞

Thanks for your report and solution!
