### ISSUE TITLE
Refresh token expires?

### ISSUE THREAD

**Issue by ba32107** [DrewML/chrome-webstore-upload#47]
Hi,

I followed the [guide](https://github.com/DrewML/chrome-webstore-upload/blob/master/How%20to%20generate%20Google%20API%20keys.md) to get a refresh token. It works, but after a few months, when I wanted to deploy a new version of my extension, I got a 400 error, and I had to regenerate the refresh token to make it work.

This seems to contradict what I've read online, apparently this token should never expire. Do you know what could have happened here?

Thanks,
Balazs

**Comment by fregante** [comment]
The refresh token does not expire. Are you sure you used the last snipped of code to generate the code instead of just using this?


44
	<img width="521" alt="Last page of OAuth" src="https://user-images.githubusercontent.com/1402241/77866731-79781480-7234-11ea-8f81-c533846d89ea.png">
45


Because this expires

**Comment by fregante** [comment]
The other possibility is that the "application" was removed/changed from either your Google account or from the Google API manager.

**Comment by ba32107** [comment]
> Are you sure you followed step 17?

Yes, I am positive. I did not change my Google API account in any way either. On February 17 I had the same problem, I regenerated the refresh token, saved it as a GitHub Secret, the upload worked perfectly. Yesterday I attempted to upload again, got the 400 error, regenerated the token again, and again it worked fine.

If I generate a new refresh token with your guide, does that make the old one expire? If so, that might explain it, because I have other applications for which I did the same thing.

**Comment by fregante** [comment]
> f I generate a new refresh token with your guide, does that make the old one expire?

To be honest, I'm not super familiar with oauth, but I wouldn't be surprised if this is the case since I used the same refresh token in my extensions since at least March 2020 (and didn't have trouble before then on Travis)

**Comment by ba32107** [comment]
Okay thanks. I now saved the same refresh token for all my apps, I guess we'll see if it works the next time I publish new version (it might be a while :) ).

I'll close this.

**Comment by fregante** [comment]
@ba32107 can you visit https://console.cloud.google.com/apis/credentials/consent and see whether your "Publish status" is set to "Testing" or "Production"?

Related: https://github.com/DrewML/chrome-webstore-upload/issues/48

**Comment by ba32107** [comment]
Hi @fregante, indeed it was set to "Testing" - good catch by Leslie in the other issue. I set it to "Production" and regenerated my refresh token.

I wasn't able to test it because I don't want to publish a new version just for this - hopefully it will work :+1

**Comment by Leslie-Wong-H** [comment]
I have succeeded in publishing a newer version automatically via ci using the regenerated refresh token. Maybe we should wait for another 7 days to check whether it is literally feasible, as the doc described, not expired, then do consider acquire it in the guide doc.

**Comment by ba32107** [comment]
Hi All,

I just published a new version with the token I generated 2+ months ago - worked like a charm!

Thanks!
