### ISSUE TITLE
The refresh token generated by following the guide here will expire in 7 days

### ISSUE THREAD

**Issue by Leslie-Wong-H** [DrewML/chrome-webstore-upload#48]
I followed this guide to get the client id, client secret, and refresh token for my extension. 

[How to generate Google API keys](https://github.com/DrewML/chrome-webstore-upload/blob/master/How%20to%20generate%20Google%20API%20keys.md)

It worked at my first attempt, but now a week later, I try to submit the extension automatically again but Travis is not working. It throws a "{\n  \"error\": \"invalid_grant\",\n  \"error_description\": \"Token has been expired or revoked.\"\n}" error. 

I have done nothing to the three generated keys. Quite weird. Then through my strategic StackOverflow search, I find this answer points the problem out. 

https://stackoverflow.com/a/65936387/8808175

> A Google Cloud Platform project with an OAuth consent screen configured for an external user type and a publishing status of "Testing" is issued a refresh token expiring in 7 days.

and the official google doc, https://developers.google.com/identity/protocols/oauth2#expiration

At the 7th step of the guide article, we just create a test user and set the publishing status to "testing". In this scenario, the refresh token generated later will expire in 7 days.

**Possible Solution:** 

After the 10th step, suggest the user go to https://console.cloud.google.com/apis/credentials/consent and set the publishing status to "in production" in advance, then go generate the credentials.

![image](https://user-images.githubusercontent.com/27696701/114265946-2da2a280-9a26-11eb-9567-c4e00f572500.png)

![image](https://user-images.githubusercontent.com/27696701/114265955-401cdc00-9a26-11eb-898f-23596a0bd026.png)

![image](https://user-images.githubusercontent.com/27696701/114265925-14015b00-9a26-11eb-87bc-0ce490697f10.png)

Just possible, haven't tested it. I have gone through the whole process of the guide, so now I just reset the publishing status and regenerate the refresh token starting from step 14. It turns out to be ok. 

Regards.

**Comment by fregante** [comment]
> At the 7th step of the guide article, we just create a test user and set the publishing status to "testing". In this scenario

The 7th step does not tell to create a test user nor to change the publish status. That's the problem here

**Comment by fregante** [comment]
Wow, they might have added an additional step… thanks for the detailed issue. I read it too fast at first.
