### ISSUE TITLE
Keys guide clarification

### ISSUE THREAD

**Issue by rasendubi** [DrewML/chrome-webstore-upload#9]
In the keys guide, there is next line
```
15. The access_code you see is actually our refreshToken.
```
and the next screen:
![](https://cloud.githubusercontent.com/assets/1402241/21518331/9b7e3b42-cc9a-11e6-8d65-cde5ba5ea105.png)

The issue is: there is no `access_code` in the response, so it means either `access_token` or `refresh_token`. Both worked for me as `refreshToken`, however, `access_token` expired sooner.

**Comment by bfred-it** [comment]
#10 fixes this. `refresh_token` was indeed the right one
